train: /content/drive/My Drive/Colab Notebooks/YOLOV8 Classification/crema_Dataset/train/images
val: /content/drive/My Drive/Colab Notebooks/YOLOV8 Classification/crema_Dataset/val/images
test: /content/drive/My Drive/Colab Notebooks/YOLOV8 Classification/crema_Dataset/test/images

nc: 2
names: ['No_Crema', 'Crema']